const actionTypes = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN__FAIL: 'LOGIN_FAIL',
    LOGIN: 'LOGIN',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT:'LOGOUT',

    // Typecar actions
    CREATE_TYPECAR_SUCCESS: 'CREATE_TYPECAR_SUCCESS',
    CREATE_TYPECAR_FAILURE: 'CREATE_TYPECAR_FAILURE',
    
}
export default actionTypes