const userRouter = require('./user')
const companyRouter = require('./company')
const typeCarRouter = require('./typecar')
const carRouter = require('./car')
const seatsRouter = require('./seats')
const voucherRouter = require('./voucher')
const tripRouter = require('./trip')
const driverTripRouter = require('./driver_trip')
const bookingRouter = require('./booking')
const dropoffRouter = require('./dropoff')
const pickupRouter = require('./pickup')
const stationRouter = require('./station')
const transactionR = require('./transaction')
const userdrivertripRouter = require('./userdrivertrip')
const promotionsRou = require('./promotions')

const {notFound, errHandler} = require('../middlewares/errHandler')
const voucher = require('../models/voucher')

const initRoutes = (app) => {
    app.use('/api/user', userRouter)
    app.use('/api/company', companyRouter)
    app.use('/api/typecar', typeCarRouter)
    app.use('/api/car', carRouter)
    app.use('/api/seats', seatsRouter)
    app.use('/api/voucher', voucherRouter)
    app.use('/api/trip', tripRouter)
    app.use('/api/drivertrip', driverTripRouter)
    app.use('/api/booking', bookingRouter)
    app.use('/api/v1/staff/drop-off', dropoffRouter)
    app.use('/api/stations', stationRouter)
    app.use('/api/v1/owner', userdrivertripRouter)
    app.use('/api/v1/staff/pick-up', pickupRouter)
    app.use('/api/v1/staff/drop-off', dropoffRouter)
    app.use('/api/v1/staff/promotion' ,promotionsRou)
    app.use('/api/payment', transactionR)
    app.use(notFound)
    app.use(errHandler)
}

module.exports = initRoutes